apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.app
      http:
        paths:
          - path: /api/payments(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: payments-clusterip-svc
                port:
                  number: 3000
          - path: /api/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-clusterip-svc
                port:
                  number: 3000
          - path: /api/tickets(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tickets-clusterip-svc
                port:
                  number: 3000
          - path: /api/orders(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: orders-clusterip-svc
                port:
                  number: 3000
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-app-svc
                port:
                  number: 3000
